_BASE_: Base-BMask-R-CNN-FPN.yaml
MODEL:
  WEIGHTS: detectron2://ImageNetPretrained/MSRA/R-50.pkl
  MASK_ON: true
  RESNETS:
    DEPTH: 50
INPUT:
  # MIN_SIZE_TRAIN: (800,)
  MIN_SIZE_TRAIN: (640, 672, 704, 736, 768, 800)
TEST:
  EVAL_PERIOD: 30000
# DATASETS:
#   TRAIN: ("coco_2017_train",)
#   TEST: ("coco_2017_val",)
# SOLVER:
#   IMS_PER_BATCH: 16
#   BASE_LR: 0.02
#   STEPS: (60000, 80000)
#   MAX_ITER: 90000
OUTPUT_DIR: "output/bmask_rcnn_r50_1x_armbench_ObjectOnly"

DATASETS:
  TRAIN: ("armbench_train_class1",)
  # TEST: ("armbench_val_class1",)
  TEST: ("armbench_test_class1",)
SOLVER:
  IMS_PER_BATCH: 2
  BASE_LR: 0.0025
  STEPS: (60000, 80000)
  MAX_ITER: 90000

SEED: 7